"""empty message

Revision ID: 58fb9ecf9920
Revises: ec0947450be7
Create Date: 2021-05-24 17:20:44.055858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58fb9ecf9920'
down_revision = 'ec0947450be7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'todolistid',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'todolistid',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
